# Generated by Django 4.1.4 on 2023-03-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelowner',
            old_name='password',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='hotelowner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hotelowner',
            name='is_hotel_owner',
        ),
        migrations.RemoveField(
            model_name='hotelowner',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='hotelowner',
            name='username',
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='city',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='country',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='hotel_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
