# Generated by Django 4.1.4 on 2023-03-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_name_hotelowner_email_hotelowner_hotel_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelOwner',
            new_name='Hotel',
        ),
    ]
