# Generated by Django 4.1.4 on 2023-03-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hotel_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
