# Generated by Django 4.1.4 on 2023-03-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_hotel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
