# Generated by Django 4.1.4 on 2023-03-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_hotel_is_hotel_hotel_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('ho_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_normal_user', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
