# Generated by Django 4.1.7 on 2023-03-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_appartment_appartmentname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartment',
            name='image',
        ),
        migrations.AddField(
            model_name='appartment',
            name='cimage',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
