# Generated by Django 4.1.7 on 2023-04-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_appartment_image_appartment_cimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='status',
            field=models.BooleanField(default='1'),
        ),
        migrations.AlterField(
            model_name='appartment',
            name='appartmentname',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='appartment',
            name='cimage',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
