# Generated by Django 4.1.7 on 2023-04-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_appartment_status_alter_appartment_appartmentname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('appartment_name', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=0)),
                ('payment_status', models.BooleanField(default=0)),
            ],
        ),
    ]
