# Generated by Django 4.1.7 on 2023-04-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='appartment_booking',
        ),
    ]
