# Generated by Django 4.1.7 on 2023-04-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_booking_appartment_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment_booking',
            name='appartment_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appartment_booking',
            name='user_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='appartment_booking',
            name='appartment_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='appartment_booking',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
