# Generated by Django 4.1.7 on 2023-05-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_appartment_booking_appartment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appartment_bookings',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('appartment_name', models.CharField(default='', max_length=50)),
                ('appartment_id', models.CharField(default='', max_length=50)),
                ('user', models.CharField(default='', max_length=50)),
                ('user_id', models.CharField(default='', max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=0)),
                ('payment_status', models.BooleanField(default=0)),
            ],
        ),
    ]
