# Generated by Django 4.1.7 on 2023-05-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_comment_ap_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appartment_bookings',
            new_name='appartment_booking2',
        ),
    ]
