# Generated by Django 4.1.7 on 2023-05-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_appartment_bookings_appartment_booking2'),
    ]

    operations = [
        migrations.CreateModel(
            name='appartment_bookings',
            fields=[
                ('ab_id', models.AutoField(primary_key=True, serialize=False)),
                ('appartment_name', models.CharField(default='', max_length=50)),
                ('appartment_id', models.CharField(default='', max_length=50)),
                ('user', models.CharField(default='', max_length=50)),
                ('user_id', models.CharField(default='', max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=0)),
                ('payment_status', models.BooleanField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='appartment_booking2',
        ),
    ]
